In [1]:
import csv

In [2]:
import pandas as pd

In [3]:
!pip install mysql-connector --upgrade

Requirement already up-to-date: mysql-connector in /opt/anaconda3/lib/python3.8/site-packages (2.2.9)

In [10]:
import mysql.connector

In [11]:
myconn = mysql.connector.connect(host = "localhost", user = "root",passwd = "chets26MY$QL",database="covid_project")

In [12]:
mycursor = myconn.cursor()

In [13]:
df = pd.read_csv('CovidDeath.csv')

In [14]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'population',
       'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths',
       'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million'],
      dtype='object')

In [30]:
df.head()

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,24/02/20,38928341.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AFG,Asia,Afghanistan,25/02/20,38928341.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AFG,Asia,Afghanistan,26/02/20,38928341.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AFG,Asia,Afghanistan,27/02/20,38928341.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AFG,Asia,Afghanistan,28/02/20,38928341.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
import numpy as np

df.fillna(0, inplace=True)
df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,24/02/20,38928341.0,1.0,1.0,0.000,0.0,0.0,...,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AFG,Asia,Afghanistan,25/02/20,38928341.0,1.0,0.0,0.000,0.0,0.0,...,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AFG,Asia,Afghanistan,26/02/20,38928341.0,1.0,0.0,0.000,0.0,0.0,...,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AFG,Asia,Afghanistan,27/02/20,38928341.0,1.0,0.0,0.000,0.0,0.0,...,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AFG,Asia,Afghanistan,28/02/20,38928341.0,1.0,0.0,0.000,0.0,0.0,...,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94140,ZWE,Africa,Zimbabwe,03/06/21,14862927.0,39092.0,61.0,34.000,1604.0,5.0,...,0.115,1.23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94141,ZWE,Africa,Zimbabwe,04/06/21,14862927.0,39144.0,52.0,32.286,1605.0,1.0,...,0.125,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94142,ZWE,Africa,Zimbabwe,05/06/21,14862927.0,39168.0,24.0,33.571,1605.0,0.0,...,0.106,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94143,ZWE,Africa,Zimbabwe,06/06/21,14862927.0,39189.0,21.0,35.000,1606.0,1.0,...,0.115,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94144,ZWE,Africa,Zimbabwe,07/06/21,14862927.0,39238.0,49.0,39.571,1611.0,5.0,...,0.163,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
mycursor.execute("CREATE TABLE CovidDeaths (iso_code nvarchar(50),continent nvarchar(50), location nvarchar(50), date nvarchar(50), population float,total_cases float,new_cases float, new_cases_smoothed float, total_deaths float,new_deaths float, new_deaths_smoothed float, total_cases_per_million float,new_cases_per_million float, new_cases_smoothed_per_million float,total_deaths_per_million float, new_deaths_per_million float,new_deaths_smoothed_per_million float, reproduction_rate float, icu_patients float,icu_patients_per_million float, hosp_patients float,hosp_patients_per_million float, weekly_icu_admissions float,weekly_icu_admissions_per_million float, weekly_hosp_admissions float,weekly_hosp_admissions_per_million float)")

In [31]:
for i,row in df.iterrows():
    mysql = "INSERT INTO covid_project.CovidDeaths( iso_code ,continent , location , date , population,total_cases ,new_cases , new_cases_smoothed , total_deaths ,new_deaths , new_deaths_smoothed , total_cases_per_million,new_cases_per_million, new_cases_smoothed_per_million ,total_deaths_per_million, new_deaths_per_million,new_deaths_smoothed_per_million , reproduction_rate , icu_patients ,icu_patients_per_million , hosp_patients ,hosp_patients_per_million , weekly_icu_admissions ,weekly_icu_admissions_per_million, weekly_hosp_admissions,weekly_hosp_admissions_per_million) VALUES(%s, %s, %s, %s, %s,%s, %s, %s, %s, %s,%s, %s, %s, %s, %s,%s, %s, %s, %s, %s,%s, %s, %s, %s, %s,%s)"
    mycursor.execute(mysql, tuple(row))
    myconn.commit()